main.cc, src/common.h, src/physics.cc, src/player.h
Also action_menu => exits run loop. Will suffice until a menu is implemented
Added as a means of exiting the game gracefully. Also, a mite bit of scaffolding for future features.
=> Bindings configured in a function

README.md
Removed Windows runtime setup. It was erroneously left in there. The build takes care of this step.
=> Update README.md - Windows Runtime Setup

main.cc
=> Windows: Fix epoxy debug callback with reinterpret_cast workaround.

.travis.yml, CMakeLists.txt, README.md, configs/keys.cfg, main.cc, nightmare.vcxproj, src/libconfig_shim.h, src/player.h
This PR includes the commit that was in #108
=> Fixing warnings and libconfig issue introduced in #108

README.md
=> MSVC: Update readme for libconfig dependency setup

configs/keys.cfg, main.cc
This removes all hard-coded inputs aside from mouse axes.
=> Keys config

configs/keys.cfg, main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/config.cc, src/input.cc, src/input.h
Revamps input configs. No longer do we need inputs_keyboard and inputs_mouse. now it's just inputs
Adds support for binding mouse axis to an action.
Adds support for mouse look x,y actions.
Fixed windows build.
Renamed player to pl in main.cc (fixed intellisense confusion)
=> Mouse axis support

main.cc
provides a tool to remove a 4x4 surface entity
=> basic surface ent remove tool for 4x4 ents

configs/input.cfg, configs/keys.cfg, main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/config.cc, src/config.h, src/settings.h
This adds some input settings (mouse invert, mouse sensitivities) to config. Also moves bindings into new settings struct.
=> More config work

src/config.cc
=> config: Don't assign NULL to nonpointers.

main.cc, src/ship_space.cc
An assortment of fixes to the raycaster and tools.
=> Raycast fixes

main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/chunk.h, src/settings.cc, src/tools.h
Cleaned up windows lib imports.
Removed unused variables
Removed unused include
Removed unnecessary access specifiers
Swapped in nullptr
Removed unnecessary virtuals
=> Cleanup: Source file tweaks that (shouldn't) affect behavior

src/tools/add_block.cc, src/tools/add_surface.cc, src/tools/remove_block.cc, src/tools/remove_surface.cc
=> tools: use override rather than redundant virtual declaration

shaders/simple.frag
=> Fix lighting on hardware that does a crap job of fract().

main.cc, src/char.cc, src/physics.h, src/ship_space.cc, src/ship_space.h
=> main: slim down projectile pool

nightmare.vcxproj
This goes with https://github.com/engineers-nightmare/windows-dependencies/pull/1
=> WindowsDeps: Update to use new built libepoxy

.travis.yml
=> travis: Fix it.

main.cc
=> Dont place ents in eye cell

main.cc, src/ship_space.cc, src/ship_space.h
=> Validate ship

main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/scopetimer.h, src/timer.h
=> Perf: FPS info. From top down frame dt, frame fps, 1/4 second fps

main.cc, shaders/sky.vert
=> sky: Put the skybox at 1, rather than 1-epsilon and fix depth func

main.cc
This handles window focus loss. We don't process any input while focus is lost.
Current state is responsible for handling focus changes.
Also addresses bug with SDL_SetRelativeMouseMode by clamping mouse axis per event.
=> Input: Handle window focus loss. Fix runaway mouse axes

src/textureset.cc
=> textureset: Fix binding for cubemaps

main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/blob.cc, src/chunk.h, src/common.h, src/component/component_system_manager.cc, src/component/component_system_manager.h, src/component/renderable_component.h, src/input.h, src/projectile/projectile.cc, src/projectile/projectile.h, src/render_data.h, src/ship_space.cc, src/wiring.cc, src/wiring.h
Lots of tidying. I say lots, but it didn't dent main.cc that much. Some tidying.
=> Misc: lots of tidying.

main.cc, src/player.h, src/tools.h, src/tools/add_block.cc, src/tools/add_surface.cc, src/tools/fire_projectile.cc, src/tools/remove_block.cc, src/tools/remove_surface.cc
Fixes #250, and makes alt-use terminate the current wiring run.
=> Alt-use plumbing for tools

main.cc, src/wiring.cc, src/wiring.h
=> wiring: Support removal.

main.cc, src/ship_space.h, src/wiring.cc, src/wiring.h
This moves the data for wiring to ship space.
=> Wiring: Move to ship space

main.cc, src/ship_space.h, src/wiring.cc, src/wiring.h
De-duplicate segments.
Allow wiring loops.
Allow starting a run off-entity.
Only stop running wire if attaching to existing.
Closes #259
=> Wiring: Misc fixes

main.cc
=> wiring: squash warnings

nightmare.sln, nightmare.vcxproj, nightmare.vcxproj.filters, src/text.cc, src/text.h
This goes with the like PR in windows-deps.
Text is disabled in this as freetype is being a pain. Will investigate stbtt
=> x64 windows

main.cc, src/mesh.cc, src/mesher.cc, src/shader.cc, src/sprites.cc, src/text.cc
=> win: fix warnings on x64

t/ship_space_test.cc
=> tests: update for scalar->vec conversion

nightmare.vcxproj, nightmare.vcxproj.filters, src/wiring/wiring.h, src/wiring/wiring_data.cc, src/wiring/wiring_data.h
=> wiring: add comms_wiring_data structs

main.cc, src/physics.cc, src/player.h
=> Player height

main.cc
=> main: fix crash on high tools

main.cc, src/ship_space.h, src/wiring/wiring.cc, src/wiring/wiring.h
This ended up being pretty cool.
=> Wire highlight

main.cc
Pulled all render out.
Only contentious part I'm aware of is modifying world state in tool preview. todo-ed it to be fixed.
=> Render refactor

src/ship_space.cc
This caused pretty weird results :)
=> ship: fix merging across +x boundary of chunk

src/component/component_system_manager.cc
=> component: don't use unsigned const &, it makes no sense.

src/ship_space.cc, src/ship_space.h
This confuses the atmo system if holes are allowed to exist inside
sealed areas.
=> ship: fix possibility of internal holes in the chunk space

src/component/component_system_manager.cc
=> Don't process messages if depowered. fix assert comment

main.cc, src/component/component_system_manager.cc
Fairly simple. See commit logs.
=> Debug tweaks

main.cc
=> entity: fix pressure sensor regression

src/tools/remove_surface.cc
=> tools: fix regression with refactor of set/remove surface

main.cc
This change adds a bit of state to the add wiring tool.
=> FSM wiring

main.cc, src/component/component_system_manager.cc, src/wiring/wiring.cc, src/wiring/wiring.h
Cleans up a bunch of duplication re broadcasting messages to connected wires.
=> Publish helper

main.cc, src/tools/tools.h
=> Tool lose focus

main.cc, src/tools/tools.h
Fix flashlight last_pos tracking + unselect + select
=> Flashlight

main.cc, src/chunk.h, src/mesher.cc, src/ship_space.cc, src/tools/add_block.cc, src/tools/remove_block.cc
Getting toward a sensible physics setup for doors.
=> Door polish part2

main.cc, src/common.h
=> main: reimplement mat_block_face more tidily.

src/component/component_system_manager.cc
=> component: trigger door-open transition as the door starts to open

main.cc
I am still working on the bugs...
=> Scale flashlight brightness with distance

src/component/component_system_manager.cc
removed uneeded trig functions by using values from the transformation matrix
used helper functions to determine surfaces parallel with door
=> cleaned up unnecessary code in set_door_state

src/tools/remove_block.cc
hookup block removal over network
=> net: add remove block support

main.cc, server.cc, src/network.cc, src/network.h, test-client.cc
Rename message type/subtype enums
Use data array accessor.
=> Net tweaks

assets/default.manifest, entities/display.ent, entities/display2.ent, entities/door.ent, entities/frobnicator.ent, entities/light.ent, entities/plaidnicator.ent, entities/pressure_sensor_1.ent, entities/pressure_sensor_2.ent, entities/proximity_sensor.ent, entities/sensor_comparator.ent, entities/switch.ent, entities/warning_light.ent, main.cc, src/asset_manager.cc, src/asset_manager.h, src/mesher.cc, src/textureset.cc, src/textureset.h, src/tools/add_block.cc, src/tools/add_entity.cc, src/tools/add_room.cc, src/tools/paint_surface.cc, src/tools/remove_block.cc, src/tools/remove_surface.cc, src/tools/remove_surface_entity.cc
This removes all `.png` references except for the ui font bits in the sprite renderer.
=> Asset man more

CMakeLists.txt, main.cc, src/common.h, src/utils/debugdraw.h, src/utils/debugdraw_gl.cc
=> Debug draw

.gitmodules, .travis.yml, CMakeLists.txt, main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/asset_manager.cc, src/asset_manager.h
The current test case sucks, and I've only tested building this on windows.
=> Implement audio using SoLoud

CMakeLists.txt, main.cc, nightmare.vcxproj, nightmare.vcxproj.filters, src/component/component_system_manager.cc, src/game_state.h, src/game_state/customize_entity_comms_inspection_state.cc, src/tools/add_entity.cc, src/tools/add_shaped_block.cc, src/tools/customize_entity.cc, src/tools/cut_wall.cc, src/tools/fire_projectile.cc, src/tools/paint_surface.cc, src/tools/remove_block.cc, src/tools/remove_entity.cc, src/tools/remove_surface.cc, src/tools/tools.h, src/tools/wiring.cc
I think this is a good start to this tool. It currently will just pop a dialog showing the name of the current entity and all children if each is wire-enabled.
=> Net inspection
