engineers-nightmare/engineers-nightmare

- configs/base/keys.cfg
- main.cc
- nightmare.sln.DotSettings
- src/config.cc
- src/config.h
- src/input.cc
- src/input.h
- src/settings.cc
- src/settings.h
This adds the ability to serialize all current settings to user config directory.
Settings menu added with ability to toggle mouse invert (and then save said change!)
Can be tested by running with/modifying the files found the following in the configs/user directory:
https://gist.github.com/RobotCaleb/8011096a45d3056d6e42
> Settings serialization - menu

- shaders/simple.frag
> shaders: use mix() instead of open-coded lerp

- main.cc
- src/ship_space.cc
- src/ship_space.h
This series tidies up the topology handling in ship_space and builds a workable atmosphere model on top of it.
The frobnicator can be added to the world to emit 0.1 mass unit of air per tick into its containing zone, up to a max pressure of 1.0 (we don't do gas temperature or other weird constants yet, so pressure=mass/volume).
Removing a surface between two spaces causes them to instantly equalize. Sealing off a space causes splitting of the zone, with mass distributed according to the volume ratio to maintain equal pressure.
> Implement atmo pressure on top of ship topology

- src/ship_space.cc
This was upside-down. Serves me right for throwing in the quick fix
without verifying it.
> ship: Fix sense of permeability early-out when adding surfaces.

- main.cc
- Made static projectile parameters good old #defines.
- Renamed `velocity` to `speed` -- it's scalar.
- Removed member initialization. In no case do we actually use the
defaults -- a particle is either initialized, or is in the dead
portion.
> main: Projectile compatibility with more compilers, and minor nits

- src/mesh.cc
- src/mesh.h
> mesh: Use less exotic vertex format, to avoid angering AMD

- main.cc
This gives us flexibility to capture variables in the lambdas, and also
makes UBSan less upset on exit (call through disposed function object)
> main: Use std::function rather than fptrs in menus

- main.cc
Fixes missing sky on AMD, various z-fighting fails. Not noticed on i965
because we don't give a Z16 surface anyway -- it's slower than Z24X8 for
obscure hardware reasons.
> main: Request at least 24 bits of depth

- main.cc
- shaders/sky.frag
- src/textureset.cc
Cube texture API is pretty weird, which is why I avoided it. We'd like to
be able to run on R600 though, so let's just deal with it...
> textureset: Add support for old-style cubes

- main.cc
- src/ship_space.cc
Previously the new topo nodes would have been smashed to zero, which causes problems if we try to walk them before something causes the topology to be rebuilt.
Fixes the crash observed in #205
> Set up valid topology for newly-spawned chunks

- main.cc
- nightmare.vcxproj
- nightmare.vcxproj.filters
- shaders/simple_instanced.vert
- src/mesh.cc
- src/mesh.h
- src/projectile/projectile.cc
- src/projectile/projectile.h
- src/shader_params.h
This switches us to use ARB_buffer_storage's persistently-mapped buffers for most small uploads, rather than using the shader_params<T> UBO path. This gives much better performance on AMD 7xxx, and should give more *consistent* performance everywhere.
> Frame data

- src/component/component_system_manager.cc
We should only be using the ce lookups for cross-component queries. When
we already have the index, going through the entity map is pure waste.
> components: tidy up some needless ce->index lookups

- src/char.cc
Use the en_ray_result_callback to properly exclude the player volume, now
that it works.
> char: set start/end positions of ray callback properly

- main.cc
- src/wiring.cc
- src/wiring.h
Just flattening the second layer of std::vector out of existence. Should be no user-facing change, but we'll get better batching of wire segment instances now.
In prep for inducing the topology over the segments.
> First part of rationalizing wiring system

- main.cc
- src/wiring.cc
- src/wiring.h
Adds support for building the set of connected-components over the wiring graph. Since we're currently add-only, this works purely incrementally. Deletes require more work (worst case is a complete rebuild)
> Hit wiring with the union-find hammer

- main.cc
- src/input.cc
- src/input.h
This adds generic support for just pressed inputs and held inputs. Hooked up just_pressed on tool use/alt-use.
If a system needs something outside of the generic, implement handling in that system.
> Input tweaks

- main.cc
- src/player.h
- src/tools.h
- src/tools/add_block.cc
- src/tools/add_surface.cc
- src/tools/fire_projectile.cc
- src/tools/remove_block.cc
- src/tools/remove_surface.cc
This allows wire attachments to be moved.
Long press primary use to initiate attach moving.
Primary use to accept new.
Alternate use to revert back.
Removes attach snap to edge logic. See #257
Closes #247
Closes #249
> Wiring move

- main.cc
If the physics component's instance data was moved (to cover a deletion),
a stale copy of the data is left behind in the vacated slot. When another
component instance is allocated, it inherits that slot. Logic in mesher.cc
assumed that if the rb ptr was non-null, it already had an rb to update
(which is important for the chunk mesher itself). Later deleting this
component instance would double-free the rb object.
> main: fix double-free of rigid bodies

- main.cc
- src/mesh.cc
- src/mesher.cc
- src/shader.cc
- src/ship_space.h
- src/sprites.cc
- src/text.cc
- src/wiring.cc
- src/wiring.h
This is rebased on #265
Extracted wiring utility functions
wired up moving, removing, creating attaches on entities
> Wiring entity remove

- main.cc
- src/component/physics_component.cc
- src/component/physics_component.h
We never actually used this, we just paid to move it around.
It didn't really make sense to store this per-entity anyway -- the physics
mesh itself isn't owned by the entity.
If we /do/ need entity-owned physics meshes, we'll add those later in a
new component (which will be quite a lot rarer)
> component: slim down physics_component data

- src/component/component_system_manager.cc
We can call attach_topo_find() on the attach itself; we don't need the
intermediate step of grabbing its data and the parent from that.
Exposes one more layer of wiring topo consolidation possibilities --
previously only the path from the parent to the wire representative
would be flattened; here we can go directly from the attach to the
wire.
> component: slim down entity->wire walking a bit

- main.cc
- src/component/component_system_manager.cc
- src/wiring/wiring.cc
- src/wiring/wiring.h
- src/wiring/wiring_data.h
See comment in source for more details.
> wiring: split read and write buffers, to avoid ordering anomalies

- main.cc
- nightmare.vcxproj
- nightmare.vcxproj.filters
- src/component/component_system_manager.cc
- src/component/component_system_manager.h
- src/component/pressure_sensor_component.cc
- src/component/pressure_sensor_component.h
light supports scalar values
pressure sensor spits out on wire
For great entertainment, in airtight room hook light up to power, comms to sensor. Add a few frobnicators (currently one frob uses one plaid power). Use frobnicators to turn on. Observe as light slowly increases in brightness.
> Pressure sensor

- main.cc
Substituted in descriptions of known wiring types.
This should be a lookup dictionary at some point.
> Wiring: Changed number to name in UI description

- src/component/component_system_manager.cc
This fixes an issue where we'd get one frame of powered state when attaching a wire with 0 power (or just a single power wire attach, same thing basically) to a power consumer.
> wiring: fix powered state bug

- main.cc
Since #305 these listen to comms. Set to initially enabled, so that
we don't have to wire comms to all gas producers.
> main: get rid of use-key hacks for directly toggling gas producers

- main.cc
Just check for switch component; fixes #304
> main: Don't show use key affordance for entities if it doesnt work

- main.cc
- src/tools/remove_block.cc
Fixes #318.
This is still a /little/ hackish in that I think we'd prefer to
support multiple surface components for entities that are doing this,
or rework the entity/block-system code completely.
Allows block entities to be more than one block tall, as the door is.
Get rid of some spurious chunk rebuilds when doing entity-only work.
Move some more logic into destroy_entity that was previously spread
everywhere.
> main/tools: Support entities multiple blocks tall

- gen/light
- main.cc
- src/component/component_system_manager.cc
- src/component/light_component.cc
- src/component/light_component.h
This updates the light component to use reader_component for its wire IO, and takes advantage of various simplifications that can now be made.
Note that all lights reevaluate their intensity based on reader state every tick now -- so tick_power_consumers doesn't need a special case.
> Simple reader use

- LICENSE.md
The "How to Apply These Terms to your New Programs" text is not part of
the license terms, but is generally included on the end of the GPL text.
> Partially revert 1d81adc03d2713e737bebb5a3360a7328c4eda4c

- main.cc
Most of the tools are already doing this in their can_use() helper. The only one
I found which isn't is the wiring tool. This will be needed for the ghetto
flashlight whose distance is limited by the tool itself.
Signed-off-by: Ben Widawsky <ben@bwidawsk.net>
> render: Let the tool determine whether or not to preview

- main.cc
- src/char.cc
- src/chunk.h
- src/physics.h
This is one of the few remaining things before we can kill entity. It also
provides the path forward to having submeshes identifiable via raycast.
> phys: change user ptr type from entity to phys_ent_ref

- main.cc
- src/component/component_system_manager.cc
- src/component/component_system_manager.h
- src/tools/remove_block.cc
- src/tools/remove_surface.cc
Fix all the weird interactions between door magic surfaces and everything else.
Fixes #323.
> tools: don't allow door magic surfaces to be ripped out

- gen/relative_position
- main.cc
- src/component/component_system_manager.cc
- src/component/relative_position_component.cc
- src/component/relative_position_component.h
- src/server_common.cc
- src/server_common.h
Entities can be turned by 90 degree snaps using alt_use
Modified doors to take rotation into account in set_door_state
Fixed entity_types array crash
Fixes #293
> Added rotations to block and surface entities.

- main.cc
- server.cc
- src/network.cc
- src/tools/add_block.cc
- src/tools/add_surface.cc
- src/tools/remove_block.cc
- src/tools/remove_surface.cc
This shifts the logic for communicating block set or surface set.
Now client will ask server to do something without the client having modified the world. The world modify comes when the server responds.
> Net pushback

- main.cc
Previous change forgot to include `<array>`
Also squash a warning when `unsigned` and `size_t` are different types.
> main: Fix the build

- src/mesh.cc
- src/mesh.h
Not consumed by any shader yet, but this adds the host-side plumbing to make it work.
> Vertex format change for explicit UV

- src/game_state/customize_entity_state.cc
- Safety improvements
- Enter key while typing in the label textbox behaves like Finish button
- Only commit the label change at the end. This decreases the "cool factor" a bit because you no longer see the label update in real time on the tool display, but makes backing out of a change easier. Not sure if this bit is good or not.
> More label work
